# Generated by Django 3.0.7 on 2020-06-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('needs_key', models.BooleanField(default=False)),
                ('full_path', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.POI')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('spawn_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawned_items', to='backend.POI')),
                ('use_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usable_items', to='backend.POI')),
            ],
        ),
    ]
