# Generated by Django 3.0.7 on 2020-06-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
    ]
