export const UPDATE_POI = 'UPDATE_POI';
export const UPDATE_OBJECTIVE = 'UPDATE_OBJECTIVE';
export const TO_PATH_DOCK = 'TO_PATH_DOCK';
export const DRAG_FROM_EMBED = 'DRAG_FROM_EMBED';

export const LIST_TO_RECEIVER = 'LIST_TO_RECEIVER';
export const RECEIVER_TO_LIST ='RECEIVER_TO_LIST';
export const LIST_TO_LIST = 'LIST_TO_LIST';

export const TO_PATH_RECEIVER = 'TO_PATH_RECEIVER';
export const FROM_PATH_RECEIVER = 'FROM_PATH_RECEIVER';