# Generated by Django 3.0.7 on 2020-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('origin_poi_name', models.CharField(max_length=100)),
                ('use_poi_name', models.CharField(max_length=100)),
            ],
        ),
    ]
