export const UPDATE_POI = 'UPDATE_POI';
export const UPDATE_OBJECTIVE = 'UPDATE_OBJECTIVE';
export const UPDATE_LIST = 'UPDATE_LIST';
export const CLEAR_REQUEST = 'CLEAR_REQUEST';
export const ADD_TILE_TO_REQUEST = 'ADD TILE';
export const REMOVE_TILE_FROM_REQUEST = 'REMOVE_TILE';
export const SHOW_ITEM_RECEIVER = 'SHOW_ITEM_RECEIVER';
export const SHOW_KEY_RECEIVER = 'SHOW_KEY_RECEIVER';

// export const UPDATE_METHODS_LIST = 'UPDATE_METHODS_LIST';
// export const UPDATE_ITEMS_LIST = 'UPDATE_ITEMS_LIST';
// export const UPDATE_KEYS_LIST = 'UPDATE_KEYS_LIST';