export const UPDATE_POI = 'UPDATE_POI';
export const UPDATE_OBJECTIVE = 'UPDATE_OBJECTIVE';
export const ADD_TO_EMBED = 'ADD_TO_EMBED';
export const REMOVE_FROM_EMBED = 'REMOVE_FROM_EMBED';

export const ADD_TO_LIST = 'ADD_TO_LIST';
export const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST';
export const REARRANGE_LIST = 'REARRANGE_LIST';

export const CLEAR_REQUEST = 'CLEAR_REQUEST';
export const ADD_TO_REQUEST = 'ADD_TO_REQUEST';
export const REMOVE_FROM_REQUEST = 'REMOVE_FROM_REQUEST';

export const SHOW_ITEM_RECEIVER = 'SHOW_ITEM_RECEIVER';
export const SHOW_KEY_RECEIVER = 'SHOW_KEY_RECEIVER';